import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Text from "funuicss/ui/text/Text"
import Container from "../Funcss/Components/Container"
import Breadcrumb from "../Funcss/Components/Breadcrumb"
import Button from "funuicss/ui/button/Button"
import Icon from "../Funcss/Components/Icon"
import Card from "funuicss/ui/card/Card";
import Input from 'funuicss/ui/input/Input';
import IconicInput from '../Funcss/Components/IconicInput';
import Div from '../Funcss/Components/Div';
import Section from '../Funcss/Components/Section';
import Grid from '../Funcss/Components/Grid';
import Col from '../Funcss/Components/Col';
export default function Home() {
  return (
    <div className="designBg home">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

     
<Card 
funcss='padding-40'
maxWidth='400px'
header={<>
<Text heading="h1" text="Login Account" block />
<Text  text="Enter your email and password to login" block />
</>}
body={<>
<Grid>
<Col sm={12} md={12} lg={12} funcss="section">
<Text
      text='Email'
      size='small'
      color='primary'
      bold
      block
      funcss='margin-bottom-10'
      />
<Input type="email"  fullWidth bordered  />
    </Col>
    <Col sm={12} md={12} lg={12} funcss="section">
      <Text
      text='Password'
      size='small'
      color='primary'
      bold
      block
      funcss='margin-bottom-10'
      />
    <Input type="password"  fullWidth bordered  />
    </Col>
</Grid>
</>}

footer={        <Button text="Login" color="white" bg="primary" fullWidth
onClick={()=>window.location.assign("/dashboard")}
/>}

/>



    </div>
  )
}
