import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Container from "../../Funcss/Components/Container"
import Breadcrumb from "../../Funcss/Components/Breadcrumb"
import Button from "funuicss/ui/button/Button"
import Icon from "../../Funcss/Components/Icon"
import Card from "../../Funcss/Components/Card";
import IconicInput from '../../Funcss/Components/IconicInput';
import Div from '../../Funcss/Components/Div';
import Section from 'funuicss/ui/specials/Section';
import Grid from '../../Funcss/Components/Grid';
import Col from '../../Funcss/Components/Col';
import Navbar from './../navBar';
import Text from 'funuicss/ui/text/Text'
import Input from 'funuicss/ui/input/Input';

export default function Category() {
  return (
    <div className="bgHome">
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
<Navbar />
   <div className="main">
      
<Card funcss="width-600-max center white round-edge padding-20 ">

<div className="padding">
<Text heading="h1" text="New Category" />
<Text text="Enter all details correctly before submitting the form" block />
</div>
<Section gap={2}>
<Input type="text" label="Category Name" fullWidth  />
</Section>
<div className="padding">
        <Button text="Add Book" color="white" bg="primary" raised bold
        onClick={()=>window.location.assign("/dashboard")}
        />
    </div>
</Card>

   </div>

    </div>
  )
}
